<a href="https://colab.research.google.com/github/Tomaz4lves/Biblioteca_pandas/blob/main/Modelagem_de_dados.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Preparando o dataset para modelagem de dados**

In [4]:
pip install chardet

Requirement already satisfied: chardet in /usr/local/lib/python3.10/dist-packages (5.2.0)

In [5]:
import pandas as pd
import datetime
from datetime import date

In [6]:
commerce = pd.read_csv("data.csv", encoding="cp1252")

In [7]:
commerce.head()

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,12/1/2010 8:26,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,12/1/2010 8:26,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,12/1/2010 8:26,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,12/1/2010 8:26,3.39,17850.0,United Kingdom

In [8]:
commerce.describe()

            Quantity      UnitPrice     CustomerID
count  541909.000000  541909.000000  406829.000000
mean        9.552250       4.611114   15287.690570
std       218.081158      96.759853    1713.600303
min    -80995.000000  -11062.060000   12346.000000
25%         1.000000       1.250000   13953.000000
50%         3.000000       2.080000   15152.000000
75%        10.000000       4.130000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [9]:
nulo = commerce.isna().sum()
print(nulo)

InvoiceNo           0
StockCode           0
Description      1454
Quantity            0
InvoiceDate         0
UnitPrice           0
CustomerID     135080
Country             0
dtype: int64

In [10]:
sn_commerce = commerce = commerce.dropna()
nulo = commerce.isna().sum()
print(nulo)

InvoiceNo      0
StockCode      0
Description    0
Quantity       0
InvoiceDate    0
UnitPrice      0
CustomerID     0
Country        0
dtype: int64

In [11]:
commerce.describe()

            Quantity      UnitPrice     CustomerID
count  406829.000000  406829.000000  406829.000000
mean       12.061303       3.460471   15287.690570
std       248.693370      69.315162    1713.600303
min    -80995.000000       0.000000   12346.000000
25%         2.000000       1.250000   13953.000000
50%         5.000000       1.950000   15152.000000
75%        12.000000       3.750000   16791.000000
max     80995.000000   38970.000000   18287.000000

In [12]:
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 406829 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    406829 non-null  object
 1   StockCode    406829 non-null  object
 2   Description  406829 non-null  object
 3   Quantity     406829 non-null  int64
 4   InvoiceDate  406829 non-null  object
 5   UnitPrice    406829 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      406829 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 27.9+ MB

In [13]:
commerce = commerce[commerce['UnitPrice'] > 1]

In [14]:
commerce = commerce[commerce['Quantity'] > 1]

In [15]:
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 242360 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    242360 non-null  object
 1   StockCode    242360 non-null  object
 2   Description  242360 non-null  object
 3   Quantity     242360 non-null  int64
 4   InvoiceDate  242360 non-null  object
 5   UnitPrice    242360 non-null  float64
 6   CustomerID   242360 non-null  float64
 7   Country      242360 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 16.6+ MB

In [16]:
commerce = commerce.drop_duplicates()

In [17]:
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 241354 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    241354 non-null  object
 1   StockCode    241354 non-null  object
 2   Description  241354 non-null  object
 3   Quantity     241354 non-null  int64
 4   InvoiceDate  241354 non-null  object
 5   UnitPrice    241354 non-null  float64
 6   CustomerID   241354 non-null  float64
 7   Country      241354 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 16.6+ MB

In [18]:
commerce['Quantity'] = commerce['Quantity'].astype('int64')
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 241354 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    241354 non-null  object
 1   StockCode    241354 non-null  object
 2   Description  241354 non-null  object
 3   Quantity     241354 non-null  int64
 4   InvoiceDate  241354 non-null  object
 5   UnitPrice    241354 non-null  float64
 6   CustomerID   241354 non-null  float64
 7   Country      241354 non-null  object
dtypes: float64(2), int64(1), object(5)
memory usage: 16.6+ MB

In [19]:
commerce['CustomerID'] = commerce['CustomerID'].astype('int64')
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 241354 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    241354 non-null  object
 1   StockCode    241354 non-null  object
 2   Description  241354 non-null  object
 3   Quantity     241354 non-null  int64
 4   InvoiceDate  241354 non-null  object
 5   UnitPrice    241354 non-null  float64
 6   CustomerID   241354 non-null  int64
 7   Country      241354 non-null  object
dtypes: float64(1), int64(2), object(5)
memory usage: 16.6+ MB

In [20]:
commerce['InvoiceDate'] = pd.to_datetime(commerce['InvoiceDate'])
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 241354 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    241354 non-null  object
 1   StockCode    241354 non-null  object
 2   Description  241354 non-null  object
 3   Quantity     241354 non-null  int64
 4   InvoiceDate  241354 non-null  datetime64[ns]
 5   UnitPrice    241354 non-null  float64
 6   CustomerID   241354 non-null  int64
 7   Country      241354 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 16.6+ MB

In [21]:
commerce = commerce[commerce['Quantity'] < 10000]
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 241352 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    241352 non-null  object
 1   StockCode    241352 non-null  object
 2   Description  241352 non-null  object
 3   Quantity     241352 non-null  int64
 4   InvoiceDate  241352 non-null  datetime64[ns]
 5   UnitPrice    241352 non-null  float64
 6   CustomerID   241352 non-null  int64
 7   Country      241352 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 16.6+ MB

In [22]:
commerce = commerce[commerce['UnitPrice'] < 5000]
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 241352 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    241352 non-null  object
 1   StockCode    241352 non-null  object
 2   Description  241352 non-null  object
 3   Quantity     241352 non-null  int64
 4   InvoiceDate  241352 non-null  datetime64[ns]
 5   UnitPrice    241352 non-null  float64
 6   CustomerID   241352 non-null  int64
 7   Country      241352 non-null  object
dtypes: datetime64[ns](1), float64(1), int64(2), object(4)
memory usage: 16.6+ MB

In [23]:
commerce.describe()

            Quantity      UnitPrice     CustomerID
count  241352.000000  241352.000000  241352.000000
mean       12.019005       3.338028   15191.892791
std        35.367896       3.665933    1715.199820
min         2.000000       1.010000   12347.000000
25%         3.000000       1.650000   13767.000000
50%         6.000000       2.100000   15039.000000
75%        12.000000       3.950000   16713.000000
max      3114.000000     649.500000   18287.000000

In [24]:
commerce['TotalPrice'] = commerce['Quantity'] * commerce['UnitPrice']

In [25]:
commerce['TotalPrice'] = commerce['TotalPrice'].astype('int64')
commerce.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 241352 entries, 0 to 541908
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    241352 non-null  object
 1   StockCode    241352 non-null  object
 2   Description  241352 non-null  object
 3   Quantity     241352 non-null  int64
 4   InvoiceDate  241352 non-null  datetime64[ns]
 5   UnitPrice    241352 non-null  float64
 6   CustomerID   241352 non-null  int64
 7   Country      241352 non-null  object
 8   TotalPrice   241352 non-null  int64
dtypes: datetime64[ns](1), float64(1), int64(3), object(4)
memory usage: 18.4+ MB

In [26]:
final_date = commerce['InvoiceDate'].max()
print(final_date)

2011-12-09 12:50:00

In [27]:
top10country = commerce.groupby('Country')['TotalPrice'].sum().nlargest(10)
print(top10country)

Country
United Kingdom    5780362
Netherlands        243907
EIRE               224016
Germany            192257
France             168137
Australia          122079
Spain               53640
Switzerland         49300
Belgium             33413
Japan               31789
Name: TotalPrice, dtype: int64

In [28]:
top10product = commerce.groupby('Description')['Quantity'].sum().nlargest(10)
print(top10product)

Description
JUMBO BAG RED RETROSPOT               45959
WHITE HANGING HEART T-LIGHT HOLDER    36566
ASSORTED COLOUR BIRD ORNAMENT         35241
RABBIT NIGHT LIGHT                    27082
RED  HARMONICA IN BOX                 20867
VICTORIAN GLASS HANGING T-LIGHT       20286
JUMBO BAG PINK POLKADOT               20059
LUNCH BAG RED RETROSPOT               17441
JUMBO BAG STRAWBERRY                  16702
HEART OF WICKER SMALL                 16681
Name: Quantity, dtype: int64

In [29]:
commerce['month'] = commerce['InvoiceDate'].dt.month
SalesDate = commerce.groupby('month')['TotalPrice'].sum()
print(SalesDate)

month
1     414092
2     364706
3     487005
4     367235
5     555312
6     553097
7     488828
8     535795
9     796596
10    840380
11    946223
12    762662
Name: TotalPrice, dtype: int64

In [39]:
df_top_paises = commerce[commerce['Country'].isin(top10country.index)]
SCD = df_top_paises.groupby(['month', 'Country'])['TotalPrice'].sum().unstack()
print(SCD.head(10))

Country  Australia  Belgium     EIRE   France  Germany   Japan  Netherlands  \
month
1           7859.0    998.0  20730.0  15436.0  14412.0     NaN      22763.0
2          12558.0   1810.0   8729.0   6593.0   8688.0  5306.0      19403.0
3          15552.0   2635.0  15408.0  11990.0  12274.0    15.0      19982.0
4            414.0   1700.0   6428.0   3532.0  10451.0  4202.0       2809.0
5          11439.0   1983.0  13975.0  14928.0  21955.0  1070.0      24858.0
6          22298.0   3440.0  16487.0  13786.0  11009.0   515.0      21953.0
7           2838.0   1975.0  36510.0   7983.0  13216.0  3479.0          NaN
8          20891.0   2880.0  14468.0  11832.0  16445.0     NaN      33418.0
9           3970.0   3768.0  34973.0  19485.0  14787.0     NaN      24395.0
10         16476.0   4411.0  19430.0  21665.0  25986.0  1878.0      34915.0

Country   Spain  Switzerland  United Kingdom
month
1        9228.0       3364.0        302582.0
2        1881.0       2458.0        287233.0
3        4786.0       1562.0        381706.0
4        1349.0       1892.0        324512.0
5        2861.0       2937.0        451023.0
6        2730.0       7141.0        438348.0
7        6720.0       3519.0        394264.0
8        2712.0       4079.0        410803.0
9        4309.0       7179.0        663978.0
10       7401.0       6555.0        672344.0